# Generated by Django 5.1.3 on 2024-12-04 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badges',
            options={'verbose_name_plural': 'Badges'},
        ),
        migrations.AlterModelOptions(
            name='certifications',
            options={'verbose_name_plural': 'Certification'},
        ),
    ]
