# Generated by Django 5.1.3 on 2024-12-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_badges_options_alter_certifications_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('project', models.ImageField(upload_to='project/')),
                ('alt_text', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('ghLink', models.CharField(max_length=500)),
                ('demoLink', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Project',
            },
        ),
    ]
